name: Build CNPG image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag or branch that will be used as the base image for the CNPG Operator (default: v1.25.0 )"
        required: false
        default: "v1.25.0"

jobs:
  build-cnpg:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      # - name: Setup Docker
      #   uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: linux/amd64
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: docker version
        run: |
          set -x
          docker version
          docker run --rm hello-world
          
      - name: Checkout CNPG Repository
        uses: actions/checkout@v4
        with:
          repository: 'cloudnative-pg/cloudnative-pg'
          ref: ${{ github.event.inputs.tag }}
          path: 'cloudnative-pg'

      - name: Build CNPG Image
        run: |
          cd cloudnative-pg
          find . -name .git -a -type d -prune -o -type f -exec sed -i -e 's|postgresql.cnpg.io|postgresql.cnpg.noobaa.io|g' -e 's|postgresql-cnpg-io|postgresql-cnpg-noobaa-io|g' {} +
          make CONTROLLER_IMG=docker.io/dannyzaken/cloudnative-pg-testing:${{ github.event.inputs.tag }} insecure="true" docker-build

      - name: Login to docker.io Registry
        run: echo ${{ secrets.GHACTIONSDOCKERHUB }} | docker login  -u ${{ secrets.GHACTIONSDOCKERHUBNAME }} --password-stdin

      - name: Push CNPG Image to Dockerhub
        run: docker push docker.io/dannyzaken/cloudnative-pg-testing:${{ github.event.inputs.tag }}
