name: Manual noobaa-operator Build Dispatch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to Build From"
        required: true
      tag:
        description: "Additional tag for the build (such as alpha, beta, etc.) - Optional"
        default: ""

jobs:
  manual-build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'dannyzaken/noobaa-operator'
          ref: ${{ github.event.inputs.branch }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Prepare Suffix
        id: suffix
        if: ${{ github.event.inputs.tag != '' }}
        run: echo ::set-output name=suffix::"-${{ github.event.inputs.tag }}"

#       - name: Prepare Tags
#         id: prep
#         run: |
#           DOCKER_OPERATOR_IMAGE=dannyzaken/noobaa-operator
#           VERSION="${{ steps.date.outputs.date }}"
#           echo "::warning ${VERSION}"
#           OPERATOR_TAGS="${DOCKER_OPERATOR_IMAGE}:${{ github.event.inputs.branch }}-${VERSION}${{ steps.suffix.outputs.suffix }}"
#           echo "::warning ${OPERATOR_TAGS}"
#           echo ::set-output name=basetags::${BASE_TAGS}
#           echo ::set-output name=buildertags::${BUILDER_TAGS}
#           echo ::set-output name=operatortags::${OPERATOR_TAGS}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GHACTIONSDOCKERHUB }} | docker login -u ${{ secrets.GHACTIONSDOCKERHUBNAME }} --password-stdin

      - name: Build & Push Docker Images to DockerHub
        env:
          DOCKERHUB_OWNER: ${{ secrets.GHACTIONSDOCKERHUBNAME }}
        run: |
          make image IMAGE=dannyzaken/noobaa-operator:${{ github.event.inputs.branch }}-${{ steps.date.outputs.date }} || true
          ls -l build/_output/bin
          docker push dannyzaken/noobaa-operator:${{ github.event.inputs.branch }}-${{ steps.date.outputs.date }}

